### ISSUE TITLE
您好，请问你用pytorch复现的JNSKR，有没有做基线对比啊？

### ISSUE THREAD

**Issue by cr2779711964** [liulu1998/JNSKR-pytorch#1]

**Comment by liulu1998** [comment]
没有

**Comment by cr2779711964** [comment]
您好，请问你跑的时候遇到过这样的错误吗（AttributeError: 'NoneType' object has no attribute 'test_user_dict'（batch_result = pool.map(test_one_user, user_batch_rating_uid)这是错误的地方））？你是在window上跑的还是linux上啊？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月14日(星期六) 晚上9:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liulu1998/JNSKR-pytorch] 您好，请问你用pytorch复现的JNSKR，有没有做基线对比啊？ (Issue #1)





 
没有

**Comment by liulu1998** [comment]
没有遇到过。
Linux，Ubuntu 18.04
