### ISSUE TITLE
代码跑不通

### ISSUE THREAD

**Issue by cr2779711964** [liulu1998/JNSKR-pytorch#2]
您好，请问你跑的时候遇到过这样的错误吗？你是在window上跑的还是linux上啊，我在windows上跑的时候遇到下面的问题
AttributeError: 'NoneType' object has no attribute 'test_user_dict'（batch_result = pool.map(test_one_user, user_batch_rating_uid)这是错误的地方）

**Comment by liulu1998** [comment]
您已运行到了测试阶段，`main.py` 中的 `test_set` 变量被正确初始化了吗？

**Comment by cr2779711964** [comment]
我现在就是这个test_set 变量不知道怎么争取初始化才一直报错，昨天试了好久都没有成功
